# Decision Tree Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

### setting the date column 

In [2]:
data = pd.read_csv('maharashtra_final_2.csv')
data['Date'].head()

0    27/11/2011
1    22/11/2011
2    23/11/2011
3    24/11/2011
4    25/11/2011
Name: Date, dtype: object

In [3]:
import datetime as dt
data['Date'] = pd.to_datetime(data['Date'])
data['Date'].head()

0   2011-11-27
1   2011-11-22
2   2011-11-23
3   2011-11-24
4   2011-11-25
Name: Date, dtype: datetime64[ns]

### getting the empty value 

In [4]:
data[data == np.inf] = np.nan
data.fillna(data.mean() , inplace = True)

In [5]:
X = data.iloc[: , [0,1,2,4]].values
X

array([[2011, 'Chandrapur', 'Other', 11],
       [2011, 'Chandrapur', 'Other', 11],
       [2011, 'Chandrapur', 'Other', 11],
       ...,
       [2020, 'Yavatmal', 'Desi', 7],
       [2020, 'Yavatmal', 'Desi', 7],
       [2020, 'Yavatmal', 'Desi', 7]], dtype=object)

In [6]:
print(X[:,1])

['Chandrapur' 'Chandrapur' 'Chandrapur' ... 'Yavatmal' 'Yavatmal'
 'Yavatmal']


In [7]:
from sklearn.preprocessing import LabelEncoder
le_1 = LabelEncoder()
le_2 = LabelEncoder()
X[:,1] = le_1.fit_transform(X[:,1])
X[:,2] = le_2.fit_transform(X[:,2])
pd.DataFrame(X).to_csv('LabelEncoded_maharashtra_final.csv')
X

array([[2011, 0, 8, 11],
       [2011, 0, 8, 11],
       [2011, 0, 8, 11],
       ...,
       [2020, 6, 1, 7],
       [2020, 6, 1, 7],
       [2020, 6, 1, 7]], dtype=object)

In [8]:
y = data.iloc[:,5].values
y

array([4000, 3850, 3900, ..., 5229, 5196, 5220], dtype=int64)

### train test split 

In [9]:
from sklearn.model_selection import train_test_split as tts
X_train ,X_test, y_train, y_test = tts(X,y,test_size = 0.2,random_state = 0)
y_train

array([4200, 4850, 4650, ..., 1965, 4800, 5180], dtype=int64)

In [10]:
X_train

array([[2013, 5, 4, 11],
       [2016, 2, 1, 6],
       [2016, 4, 8, 5],
       ...,
       [2018, 3, 1, 11],
       [2016, 3, 1, 5],
       [2011, 5, 8, 1]], dtype=object)

## Training the Decision Tree Regression model on the Training set

In [11]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()
dtr.fit(X_train,y_train)

DecisionTreeRegressor()

In [12]:
print(X_test)

[[2018 5 2 7]
 [2017 6 8 10]
 [2017 3 1 4]
 ...
 [2016 6 4 1]
 [2020 6 1 2]
 [2014 6 8 11]]


In [13]:
y_pred_dtr = dtr.predict(X_test)
print(np.concatenate((y_pred_dtr.reshape(len(y_pred_dtr),1), y_test.reshape(len(y_test),1)),1))

[[4600.         4600.        ]
 [5224.         5224.        ]
 [5277.14285714 5260.        ]
 ...
 [4523.25       4560.        ]
 [4978.92307692 5395.        ]
 [4500.         4500.        ]]


In [14]:
import joblib as jb
jb.dump(dtr,'decision_tree_maharashtra.ml')
jb.dump(dtr,'decision_tree_maharashtra.pkl')

['decision_tree_maharashtra.pkl']

In [15]:
jb.dump(le_1,'le_1.pkl')
jb.dump(le_2,'le_2.pkl')

['le_2.pkl']

## Evaluating the Model Performance

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_dtr)

0.8943023589095553

### Random forest Regression 

In [17]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr.fit(X_train,y_train)

RandomForestRegressor()

In [18]:
y_pred_rfr = rfr.predict(X_test)
print(np.concatenate((y_pred_rfr.reshape(len(y_pred_rfr),1), y_test.reshape(len(y_test),1)),1))

[[4600.         4600.        ]
 [5224.         5224.        ]
 [5277.51714881 5260.        ]
 ...
 [4523.86029977 4560.        ]
 [4984.92288628 5395.        ]
 [4500.         4500.        ]]


In [19]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_rfr)

0.8943062291613287

In [20]:
import joblib as jb
jb.dump(rfr,'random_forest_maharashtra.ml')
jb.dump(rfr,'random_forest_maharashtra.pkl')

['random_forest_maharashtra.pkl']