# Decision Tree Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

### setting the date column 

In [2]:
data = pd.read_csv('tamil_nadu_final.csv')
data['Date'].head()

0    12/09/2011
1    13/09/2011
2    14/09/2011
3    15/09/2011
4    16/09/2011
Name: Date, dtype: object

In [3]:
import datetime as dt
data['Date'] = pd.to_datetime(data['Date'])
data['Date'].head()

0   2011-12-09
1   2011-09-13
2   2011-09-14
3   2011-09-15
4   2011-09-16
Name: Date, dtype: datetime64[ns]

### getting the empty value 

In [4]:
data[data == np.inf] = np.nan
data.fillna(data.mean() , inplace = True)

In [5]:
X = data.iloc[: , [0,1,2,4]].values
X

array([[2011, 'Dindigul', 'MCU 5', 9],
       [2011, 'Dindigul', 'MCU 5', 9],
       [2011, 'Dindigul', 'MCU 5', 9],
       ...,
       [2020, 'Villupuram', 'Other', 10],
       [2020, 'Villupuram', 'Other', 10],
       [2020, 'Villupuram', 'Other', 10]], dtype=object)

In [6]:
print(X[:,1])

['Dindigul' 'Dindigul' 'Dindigul' ... 'Villupuram' 'Villupuram'
 'Villupuram']


In [7]:
from sklearn.preprocessing import LabelEncoder
le_1 = LabelEncoder()
le_2 = LabelEncoder()
X[:,1] = le_1.fit_transform(X[:,1])
X[:,2] = le_2.fit_transform(X[:,2])
pd.DataFrame(X).to_csv('LabelEncoded_tamil_nadu_final.csv')
X

array([[2011, 0, 2, 9],
       [2011, 0, 2, 9],
       [2011, 0, 2, 9],
       ...,
       [2020, 7, 4, 10],
       [2020, 7, 4, 10],
       [2020, 7, 4, 10]], dtype=object)

In [8]:
y = data.iloc[:,5].values
y

array([3800, 3800, 3200, ..., 4809, 5192, 5494], dtype=int64)

### train test split 

In [9]:
from sklearn.model_selection import train_test_split as tts
X_train ,X_test, y_train, y_test = tts(X,y,test_size = 0.2,random_state = 0)
y_train

array([3800, 3500, 3600, ..., 6000, 3800, 3000], dtype=int64)

In [10]:
X_train

array([[2015, 8, 2, 6],
       [2011, 5, 4, 6],
       [2015, 6, 4, 6],
       ...,
       [2016, 4, 4, 9],
       [2014, 6, 1, 10],
       [2011, 5, 4, 9]], dtype=object)

## Training the Decision Tree Regression model on the Training set

In [11]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()
dtr.fit(X_train,y_train)

DecisionTreeRegressor()

In [12]:
print(X_test)

[[2016 0 4 1]
 [2017 2 2 5]
 [2011 6 2 9]
 ...
 [2013 1 1 9]
 [2018 1 4 8]
 [2011 2 4 6]]


In [13]:
y_pred_dtr = dtr.predict(X_test)
print(np.concatenate((y_pred_dtr.reshape(len(y_pred_dtr),1), y_test.reshape(len(y_test),1)),1))

[[3841.66666667 3800.        ]
 [4000.         4000.        ]
 [3510.         3500.        ]
 ...
 [5780.43478261 5450.        ]
 [5944.19230769 6422.        ]
 [2533.63636364 2550.        ]]


In [14]:
import joblib as jb
jb.dump(dtr,'decision_tree_tamil_nadu.ml')
jb.dump(dtr,'decision_tree_tamil_nadu.pkl')

['decision_tree_tamil_nadu.pkl']

## Evaluating the Model Performance

In [15]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_dtr)

0.8570104365743093

In [16]:
y_pred = dtr.predict([[2020,le_1.transform(['Dindigul']),le_2.transform(['MCU 5']),2]])

In [17]:
print(y_pred)

[5174.34782609]


### Random forest Regression 

In [18]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr.fit(X_train,y_train)

RandomForestRegressor()

In [19]:
y_pred_rfr = rfr.predict(X_test)
print(np.concatenate((y_pred_rfr.reshape(len(y_pred_rfr),1), y_test.reshape(len(y_test),1)),1))

[[3844.06200531 3800.        ]
 [4000.         4000.        ]
 [3510.88874695 3500.        ]
 ...
 [5784.27657656 5450.        ]
 [5929.94960851 6422.        ]
 [2534.11973911 2550.        ]]


In [20]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_rfr)

0.858175232082656

In [21]:
import joblib as jb
jb.dump(rfr,'random_forest_tamil_nadu.ml')
jb.dump(rfr,'random_forest_tamil_nadu.pkl')

['random_forest_tamil_nadu.pkl']