# Decision Tree Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

### setting the date column 

In [2]:
data = pd.read_csv('andhra_pradesh_final.csv')
data['Date'].head()

0    07/02/2011
1    15/09/2011
2    01/01/2011
3    02/01/2011
4    03/01/2011
Name: Date, dtype: object

In [3]:
import datetime as dt
data['Date'] = pd.to_datetime(data['Date'])
data['Date'].head()

0   2011-07-02
1   2011-09-15
2   2011-01-01
3   2011-02-01
4   2011-03-01
Name: Date, dtype: datetime64[ns]

### getting the empty value 

In [4]:
data[data == np.inf] = np.nan
data.fillna(data.mean() , inplace = True)

In [5]:
X = data.iloc[: , [0,1,2,4]].values
X

array([[2011, 'Guntur', 'Mungari  (Ginned)', 2],
       [2011, 'Guntur', 'N-44', 9],
       [2011, 'Guntur', 'Other', 1],
       ...,
       [2018, 'Guntur', 'Cotton (Unginned)', 3],
       [2018, 'Guntur', 'Cotton (Unginned)', 3],
       [2018, 'Guntur', 'Cotton (Unginned)', 3]], dtype=object)

In [6]:
print(X[:,1])

['Guntur' 'Guntur' 'Guntur' ... 'Guntur' 'Guntur' 'Guntur']


In [7]:
from sklearn.preprocessing import LabelEncoder
le_1 = LabelEncoder()
le_2 = LabelEncoder()
X[:,1] = le_1.fit_transform(X[:,1])
X[:,2] = le_2.fit_transform(X[:,2])
pd.DataFrame(X).to_csv('LabelEncoded_andhra_pradesh_final.csv')
X

array([[2011, 0, 10, 2],
       [2011, 0, 11, 9],
       [2011, 0, 12, 1],
       ...,
       [2018, 0, 1, 3],
       [2018, 0, 1, 3],
       [2018, 0, 1, 3]], dtype=object)

In [8]:
y = data.iloc[:,5].values
y

array([3700, 3000, 3600, ..., 3100, 3100, 3300], dtype=int64)

### train test split 

In [9]:
from sklearn.model_selection import train_test_split as tts
X_train ,X_test, y_train, y_test = tts(X,y,test_size = 0.2,random_state = 0)
y_train

array([3100, 4000, 3500, ..., 3500, 3900, 4000], dtype=int64)

In [10]:
X_train

array([[2011, 0, 1, 9],
       [2015, 0, 7, 7],
       [2011, 0, 7, 10],
       ...,
       [2012, 0, 7, 6],
       [2013, 0, 7, 4],
       [2014, 0, 12, 2]], dtype=object)

## Training the Decision Tree Regression model on the Training set

In [11]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()
dtr.fit(X_train,y_train)

DecisionTreeRegressor()

In [12]:
print(X_test)

[[2016 0 7 6]
 [2018 0 7 1]
 [2014 0 7 6]
 ...
 [2018 0 12 1]
 [2018 0 7 3]
 [2011 0 7 4]]


In [13]:
y_pred_dtr = dtr.predict(X_test)
print(np.concatenate((y_pred_dtr.reshape(len(y_pred_dtr),1), y_test.reshape(len(y_test),1)),1))

[[4121.73913043 4100.        ]
 [4546.         4600.        ]
 [4533.33333333 4700.        ]
 ...
 [4700.         4700.        ]
 [4276.92307692 4600.        ]
 [5138.46153846 4500.        ]]


In [14]:
import joblib as jb
jb.dump(dtr,'decision_tree_andhra_pradesh.ml')
jb.dump(dtr,'decision_tree_andhra_pradesh.pkl')

['decision_tree_andhra_pradesh.pkl']

In [15]:
jb.dump(le_1,'le_1.pkl')
jb.dump(le_2,'le_2.pkl')

['le_2.pkl']

## Evaluating the Model Performance

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_dtr)

0.8804427884226844

### Random forest Regression 

In [17]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr.fit(X_train,y_train)

RandomForestRegressor()

In [18]:
y_pred_rfr = rfr.predict(X_test)
print(np.concatenate((y_pred_rfr.reshape(len(y_pred_rfr),1), y_test.reshape(len(y_test),1)),1))

[[4122.61891773 4100.        ]
 [4545.89411358 4600.        ]
 [4529.68444385 4700.        ]
 ...
 [4700.         4700.        ]
 [4279.72131964 4600.        ]
 [5136.52234199 4500.        ]]


In [19]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_rfr)

0.8814369805859167

In [20]:
import joblib as jb
jb.dump(rfr,'random_forest_andhra_pradesh.ml')
jb.dump(rfr,'random_forest_andhra_pradesh.pkl')

['random_forest_andhra_pradesh.pkl']